services:
  db:
    image: postgres:16
    ports:
      - 5678:5432
    environment:
      POSTGRES_DB: mykb
      POSTGRES_USER: mykb
      POSTGRES_PASSWORD: mykb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./.keystone/postgres:/var/lib/postgresql/data
